/// Autogenerated by Targets - Edit tests.json instead of this file
import 'helpers.dart';
final String name = "Enigma Project - Python";
final String owner = "dart-targets";
final String id = "enigma-python";
final List<String> files = ["enigma.py","bombe.py"];
List<Target> getTargets() {
    var targets = [];
    targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Plugboard", "plugboard", "", -1)));targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Simple Enigma", "simple", "", -1)));targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Moderate Enigma", "moderate", "", -1)));targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Complex Enigma", "complex", "", -1)));targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Bombe Plugboard", "bombe_plug", "", -1)));targets.add(IOTarget.make("python tests.py", new InputOutput.withArgs("Full Bombe", "bombe", "", -1)));
    return targets;
}
