/// Autogenerated by Targets - Edit tests.json instead of this file
import 'helpers.dart';
final String name = "Enigma Project - Java";
final String owner = "dart-targets";
final String id = "enigma-java";
final List<String> files = ["Enigma.java","Plugboard.java","Reflector.java","Rotor.java","Bombe.java","*.java","!TestEnigma.java","!EnigmaCLI.java"];
List<Target> getTargets() {
    var targets = [];
    targets.addAll(IOTarget.makeMultiJava("TestEnigma", [new InputOutput.withArgs("Plugboard", "plugboard", "", -1), new InputOutput.withArgs("Simple Enigma", "simple", "", -1), new InputOutput.withArgs("Moderate Enigma", "moderate", "", -1), new InputOutput.withArgs("Complex Enigma", "complex", "", -1), new InputOutput.withArgs("Bombe Plugboard", "bombe_plug", "", -1), new InputOutput.withArgs("Full Bombe", "bombe", "", -1), ]));
    return targets;
}
